### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/opensearch-dsl-py#101]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the OpenSearch DSL-PY repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| OpenSearch DSL-PY  | <li>- [x] </li> | <li>- [x] </li> | <li>- [ ] </li> | Changelog Verifier, Link Checker | https://github.com/opensearch-project/opensearch-dsl-py/issues/101 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by VachaShah** [comment]
Closing this issue since opensearch-dsl-py is merged into opensearch-py as part of https://github.com/opensearch-project/opensearch-dsl-py/issues/93
