### ISSUE TITLE
[CCI][FEATURE] Add test coverage statistics to Codecov

### ISSUE THREAD

**Issue by bl1nkker** [opensearch-project/opensearch-dsl-py#107]
### Is your feature request related to a problem?
The project currently is not integrated with codecov.io, while [many other repositories](https://app.codecov.io/gh/opensearch-project/opensearch-js) already display test coverage on the web interface.

### What solution would you like?
Add codecov integration

**Comment by wbeckler** [comment]
This repo is undertaking its final release, and the functionality has completely moved to opensearch-py. Therefore, I would suggest this issue get closed with no aciton.

**Comment by bl1nkker** [comment]
got it👍
