### ISSUE TITLE
[FEATURE] Add more params in Search.from_dict()

### ISSUE THREAD

**Issue by WalkerWang731** [opensearch-project/opensearch-dsl-py#109]
### Is your feature request related to a problem?
When I use query dict to create a Search object, this function only receive one param, no more params such as `using` `index`

Although I can use `using()` and `index()` after create object to adjust the object, but these function will copy more object in the `s = self._clone()` function.  

I think these operations are unnecessary.

### What solution would you like?
Create object In one step
```
d = {
    "query": {
        "match_all": {}
    }
}
client = object()
index = 'index1'
s = Search.from_dict(d, using=client, index=index)
```

### What alternatives have you considered?

```
s = Search.from_dict(d).using(client=client).index(index)
```
or 

```
s = Search(using=client, index=index)
s.update_from_dict(d)
```

### Do you have any additional context?
Nothing

**Comment by wbeckler** [comment]
Please take a look at opensearch-py. The dsl client was merged into that repo and deprecated here.

**Comment by saimedhi** [comment]
@WalkerWang731 
Closing this issue; feel free to reopen it in the opensearch-py repo if needed. Thanks!
