### ISSUE TITLE
[BUG] Documentation doesn't explain what this project is

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-dsl-py#37]
**What is the bug?**
The fork didn't carry a README that explains what this project is, why it exists or how to use it.

**Do you have any additional context?**
I came from https://github.com/opensearch-project/opensearch-py/issues/90, and it took me a while to figure out what the difference between opensearch-py and opensearch-dsl-py is.

**Comment by elfisher** [comment]
@VijayanB what are your thoughts on adding a sentence to the readme that outlines what this dsl client is used for. Something like "opensearch-dsl-py is a python client specifically used for build and running queries against OpenSearch."

**Comment by VijayanB** [comment]
@elfisher Agree.  I will create a PR to update the same.

**Comment by wbeckler** [comment]
@VijayanB Did you create the PR for changing the README?
