### ISSUE TITLE
Update Copyright in order to maintain consistency in OpenSearch clients

### ISSUE THREAD

**Issue by ghost** [opensearch-project/opensearch-dsl-py#41]
**What is the issue?**
The copyright message is in this [repo](https://github.com/opensearch-project/opensearch-dsl-py/blob/main/README.md#:~:text=Copyright%202020%2D2021%20Amazon.com%2C%20Inc.%20or%20its%20affiliates.%20All%20Rights%20Reserved.) is inconsistent with python's [copyright message](https://github.com/opensearch-project/opensearch-py#:~:text=Copyright%20OpenSearch%20Contributors.%20See%20NOTICE%20for%20details.). A file NOTICE.txt also needs to be added.

I attempted to do this myself, however I did not have permissions to push to a protected branch that I created. Due to my attempts to make these changes myself, the branches have been populated with `guiangumpac-update-copyright-patch` and `update-copyright`. To maintain a clean set of branches, these two branches should be removed.

**Comment by VachaShah** [comment]
Done as part of #62
