### ISSUE TITLE
Release version 2.0.0 for High Level Python client

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-dsl-py#50]
Release the client version 2.0.0. Before releasing, the following items need to be done:

- [x] [Update](https://github.com/opensearch-project/opensearch-dsl-py/blob/main/setup.py#L43) the client to use the latest version for `opensearch-py` client
- [x] Add OpenSearch 2.0 to the integration [test matrix](https://github.com/opensearch-project/opensearch-dsl-py/blob/main/.github/workflows/integration.yml#L12).
- [x]  Bump the client version to 2.0.0.
- [x]  Cut a 2.0 branch for the client.

**Comment by peterzhuamazon** [comment]
We are releasing opensearch-dsl-py right now: https://pypi.org/project/opensearch-dsl/2.0.0/

**Comment by VachaShah** [comment]
High level python client is released https://pypi.org/project/opensearch-dsl/2.0.1/
