### ISSUE TITLE
[FEATURE] Add support for inclusive naming

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/opensearch-dsl-py#60]
Add support for inclusive naming by deprecating the master nomenclature.

See meta issue https://github.com/opensearch-project/opensearch-clients/issues/16 for details.

**Comment by harshavamsi** [comment]
@VachaShah combing through the code, I don't see any references of `master` or `whitelist`. Is there anything else I should be looking for?

**Comment by VachaShah** [comment]
@harshavamsi That should be all. Since this is a high level client, there might not be any such references.
