### ISSUE TITLE
[FEATURE] Improve documentation

### ISSUE THREAD

**Issue by robertofd1995** [opensearch-project/opensearch-dsl-py#78]
### Is your feature request related to a problem?
I have to read the documentation from elastisearch-dsl-py in order to be able to use most of this library

### What solution would you like?
The actual tutorial it doesn't explain nothing about Document, Index and search classes which are the main point of this library. I understand this is kind of new, but in order for people to use your solutions Dev experience should be improved.

### What alternatives have you considered?
Read the documentation of the original library, which speaks kind of bad from this alternative versus the original

**Comment by harshavamsi** [comment]
Documentation is available here -- https://opensearch-project.github.io/opensearch-py/api-ref/helpers.html
