### ISSUE TITLE
[FEATURE] Standardize, setup, report, and increase test coverage

### ISSUE THREAD

**Issue by Xtansia** [opensearch-project/opensearch-dsl-py#80]
Setup code coverage, once reporting from CI/CD analyze the test gap and fill it.

See the meta issue https://github.com/opensearch-project/opensearch-clients/issues/30 for details.

**Comment by VachaShah** [comment]
Closing this issue since opensearch-dsl-py is being merged into opensearch-py as part of https://github.com/opensearch-project/opensearch-dsl-py/issues/93
